### ISSUE TITLE
Access to parent / guardian broken in ticket listing

### ISSUE THREAD

**Issue by sandrobonazzola** [CoderDojo/cd-common#12]
Not sure pr #11 is the root cause of the issue I'm seeing today in coderdojo brianza events, but looks like in the last week something broke the code accessing to parents / guardian while showing the list of the tickets for an event. 
Looking at the browser console looks like it's doing calls to API like:
GET: https://zen.coderdojo.com/api/2.0/profiles/parents-for-user/3012a67d-06d7-4dbc-ad63-b32e32591532
and it's receiving a 403 forbidden error.
The page I'm looking is https://zen.coderdojo.com/dashboard/my-dojos/9943615c-232b-431e-bc87-323580d62f20/events/991d84d2-c1c2-4840-acf4-af143bc02e6c/applications

Can you please check?

**Comment by Wardormeur** [comment]
Unrelated, PR #11 is to display the access of the elarning module to all adults instead of only mentors & champions :)
The error you report looks like a permission issue, we'll have a look at it on Monday :)
Also report issues on community-platform instead if possible :p

**Comment by Wardormeur** [comment]
Actually, and to be sure we have all the elements, could you send me your email by PM on forums.coderdojo.com ? My user is https://forums.coderdojo.com/user/guillaume-feliciano

**Comment by sandrobonazzola** [comment]
Can't login to the forum.
Internal error.
Oops! Looks like something went wrong!
/auth/CoderDojo/callback
failed to fetch user profile

My email address is sandro.bonazzola at gmail com
